const USER_COLLECTION_NAME = "users";
const POSITION_COLLECTION_NAME = "positions";
const POST_COLLECTION_NAME = "posts";
const GAMEAREA_COLLECTION_NAME = "gamearea";

export {
  USER_COLLECTION_NAME,
  POSITION_COLLECTION_NAME,
  POST_COLLECTION_NAME,
  GAMEAREA_COLLECTION_NAME,
};
